# Arquivo _config.yml

# Define o diretório de origem, caso use um subdiretório como "docs"
source: ./docs

# Define o diretório de saída onde os arquivos gerados serão colocados
destination: ./docs

# Nome do seu site
title: "Meu Site Jekyll"

# URL do seu site
url: "https://gianjr.github.io/Projeto/"

# Configurações de tema
theme: jekyll-theme-primer

# Outras configurações
markdown: kramdown
